language: java
jdk:
- openjdk10
- openjdk11
sudo: false
install:
- sudo apt install ant-optional
- cd apache-activemq-5.15.10/bin
- chmod +x activemq
- ./activemq start
before_script:
- cd ../../
- ant -Dlibs.CopyLibs.classpath=lib/org-netbeans-modules-java-j2seproject-copylibstask.jar
- cd ApiRest
