---
- hosts: all
  become: true
  tasks:
    - name: Instala git
      apt:
        pkg: git
        state: present
    - name: Instala python
      apt:
        pkg: python3
        state: present
    - name: Instala pip
      apt:
        pkg: python3-pip
        state: present
    - name: Instala NPM
      apt:
        pkg: npm
        state: present
    - name: Instala PM2
      npm:
        name: pm2
        global: yes
    - name: Instala RabbitMQ
      apt:
        pkg: rabbitmq-server
        state: present
    - name: Usuario
      user:
        name: nazaret
        shell: /bin/bash
    - name: SSH
      authorized_key:
        user: nazaret
        state: present
        key: "{{ lookup('file', '/home/nazaret/.ssh/id_rsa.pub') }}"
    - git:
        repo: https://github.com/nazaretrogue/Microservicio-multimedia.git
        clone: yes
        dest: ~/Microservicio-multimedia/
        force: yes
    - pip:
        requirements: ~/Microservicio-multimedia/requirements.txt
    - name: Instala make
      apt:
        pkg: make
        state: present
    - name: Inicia app
        make:
          file: ~/Microservicio-multimedia/Makefile
          target: vm-azure-app
          chdir: ~/Microservicio-multimedia
